### ISSUE TITLE
Does nuspec_description and nuspec_users really need to be required?

### ISSUE THREAD

**Issue by toby-freemarket** [OctopusDeploy/create-nuget-package-action#5]
When using the octo tool these were never require is there a reason they are now?

**Comment by benPearce1** [comment]
Hi @toby-freemarket,

The Author and Description fields were always required, but the OctopusCLI was setting them to default values if they were provided (see [here](https://github.com/OctopusDeploy/OctopusCLI/blob/master/source/Octopus.Cli/Commands/Package/PackCommand.cs#L115) and [here](https://github.com/OctopusDeploy/OctopusCLI/blob/master/source/Octopus.Cli/Commands/Package/PackCommand.cs#L118)).

Since the author was unable to be determined, since this operation would always be running in a CI build, we removed the defaults and made them mandatory.
